/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package enums;

/**
 *
 * @author hp
 */
public enum LibelleCategorie {
 acceptation_tpv,voyage_individuel_afrique,voyage_individuel_europe,voyage_individul_monde_basic,voyage_individuel_monde_plus,voyage_individuel_perinage,
 assistance_etudiant,retrocession_pool,maladie_groupe,garagiste_6a,maladie_individuel,corps_aerien,tourisme_vehicule_personnel,transport_prive_marchandise_inferieur3point5tonne,
 transport_prive_marchandise_superieur3point5tonne,taxis_ville_4a ,personnel_roues_2a3,auto_ecole,auto_location,english_mobile_chantier,ambulance,
 transport_personnel_eleve,commercial_roue_2a3,caution_soumission,caution_bon_fin,caution_avance_demarrage
 ,acceptation_credit,

 cautio_retenu_garantie,caution_proffessionnel,acceptation_rc,acceptation_incendie_autre_dommage,acceptation_autr_risque_dommage,acceptation_transport_aerien,
 acceptation_transport_maritine,acceptation_autre_transport,acceptation_caution,auto_ecole_utilitaire_taxi,auto_ecole_2a3_roues,autre_flotte,rc_chef_entreprise,
 rc_manifestation_sportif,rc_affreteur_navire,rc_aerien,rc_chef_famille,rc_proffessionel,rc_proprietaire_immeuble,rc_constructeur_navire,rc_decennal,rc_transporteur,
 rc_risque_petrolier,rc_exploitation_aviation,rc_scolaire,rc_diverse,risque_simple,risque_commerciaux,risque_industriel,global_dommage,multi_risque_habitation,
 bris_machine,tous_risque_chantier,tous_risque_informatique,tourisque_montage,global_banque,transport_fond,faculte_aerien,faculte_maritime,faculte_fluvial,
 off_shore,corps_maritime,corps_fluviaux,corps_plaissance,corps_peche,faculte_terrestre,faculte_feroviaire,corps_ferroviaire,perte_exploitation_apres_incendie,
 perte_exploitation_apres_bris_machine,perte_exploitation_apres_tri,perte_exploitation_apres_trm,incendi_accient_personnel,individuel_accident_group,
 individuel_aviation_personnel_navigation,individuel_aviation_passagers,individuel_voyage,complementaire_accident_travail,frais_funerail_group,maladi_famille,
 maladie_complementaire,maladie_association,multi_risque_sante_individuel,multirisque_sante_groupe,colletivite_public,tracteur_agricole,tracteur_forestier,
 camion_vidange,ramassage_ordur,autre_camion_tracteur,fap_sauf,tous_risque,vol,transport_faculte_maritime_terrestre_aerien,accident_caracterise,coulage,
 dommage_corps,responsabilite_cilvil,police_voyage,police_abonement,voyage_individuel,voyage_group,flotte_pack,
 caution_direct,caution_indirect,credit_insolvabilite,credit_exportation,credit_vente_temperament,credit_hypothecaire,credit_agricole,
 acceptation_corps_maritime,acceptation_off_shore,garanti_2_3_roues,flotte,tpv_car_auto_et_bus,autres;
}
